services:
  db:
    image: postgres:16
    container_name: consulta-creditos-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-creditosdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-creditosdb}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - consulta-net

  consulta-creditos-api:
    build:
      context: ./consulta-creditos-api
      dockerfile: Dockerfile
    container_name: consulta-creditos-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-creditosdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    # API exposta em porta parametrizada para evitar conflito com execução local
    ports:
      - "${API_PORT:-8086}:8080"
    networks:
      - consulta-net

  consulta-creditos-web:
    build:
      context: ./consulta-creditos-web
    container_name: consulta-creditos-web
    ports:
      - "${WEB_PORT:-8081}:80"   # Nginx escuta 80 dentro do container; expõe 8081 no host
    depends_on:
      - consulta-creditos-api
    networks:
      - consulta-net

volumes:
  dbdata:

networks:
  consulta-net: {}
